### ISSUE TITLE
Configuration steps missing for user management service

### ISSUE THREAD

**Issue by arpit2010** [airavata-courses/Blitzkrieg#33] opened 2020-02-23 02:32 UTC
While running this service, i have configured postgres with my username and password but still,
 i am facing this issue. 

![blitz1](https://user-images.githubusercontent.com/8495322/75102522-d1c75100-55ba-11ea-8b25-c5040a137e4b.JPG)
![blitz2](https://user-images.githubusercontent.com/8495322/75102523-d1c75100-55ba-11ea-8512-1a1df5d2560e.JPG)

**Comment by shindedarshan** [comment] 2020-02-25 00:16
I tried reproducing this issue on the Ubuntu VM (fresh VM created from LTS distribution of Ubuntu), and its working properly without any error.

Please follow following steps if you face any issue:

1. Install postgressql in your system by executing following commands.
     sudo apt-get install postgresql
     sudo apt-get install python-psycopg2
     sudo apt-get install libpq-dev 
2. Run python install -r requirements.txt
    This command will install all required dependencies.
3. Start user_management microservice by executing following command from the user_management directory.
    python -m src.\_\_init\_\_
If you face port already in use issue, then change the port in const.py and restart the service.

Note: After installing postgresql, it will create a default user by the name of postgres. User management micro-service uses this default user. Change password for the postgres user in URL in const.py file.

**Comment by shindedarshan** [comment] 2020-02-25 01:28
While creating new user, you might have not set the password for the user. You can set the password for the user by executing following commands. (in following example I am trying to change password of postgres user, you can changed values according to your user).
sudo -u postgres psql postgres
By running this command you will login with postgres user and open psql prompt.

Inside psql prompt run following command to change the password.
 \password postgres

This command will prompt for the new password and re-enter the password. Set password of your choice. Set the same username and password in const.py file. And start the user management micro-service. 

These steps should resolve your issue.

**Comment by shindedarshan** [comment] 2020-02-25 01:32
![Screenshot from 2020-02-24 17-31-02](https://user-images.githubusercontent.com/44418177/75206580-9dbf6d80-572b-11ea-9013-c220708e980e.png)

**Comment by shindedarshan** [comment] 2020-05-03 20:20
This issue has been resolved by the above-mentioned steps. It has been tested several times since then. Hence, I feel we are good to close this issue.

**Closed as completed by shindedarshan** 2020-05-03 20:20 UTC
